<?php

$classes = [
"Anjeer",
"Apple Fuji",
"Apple Granny Smith",
"Apple Pink Lady",
"Apple Royal Gala",
"Apple Shimla",
"Apple Small",
"Apricots Fresh",
"Apricots Fresh Packed",
"Ash Gourd Cut",
"Avocado Indian",
"Baby Corn",
"Banana Flower",
"Banana Hills",
"Banana Morris",
"Banana Nadan",
"Banana Nendran",
"Banana Poovan",
"Banana Rasthali",
"Banana Red",
"Banana Yelakki",
"Beans Bush",
"Beans Butter",
"Beans Thin Cowpea",
"Beetroot",
"Bere Elandai",
"Bitter Gourd",
"Bok Choy",
"Bottle Gourd",
"Brinjal Black Big",
"Brinjal Long",
"Brinjal Purple Striped",
"Broccoli",
"Brussels Sprout",
"Cabbage",
"Cabbage Red",
"Capsicum",
"Capsicum Red",
"Capsicum Yellow",
"Carrot Ooty",
"Cassave",
"Cauliflower",
"Celery Leaves",
"Chilli Long Bajji",
"Chinese Cabbage",
"Chow Chow",
"Citron",
"Cluster Beans",
"Coconut",
"Coconut Flower",
"Coriander Leaves",
"Cucumber",
"Curry Leaves",
"Custard Apple",
"Dates Fresh Yellow",
"Dragon Fruit Yellow",
"Dragon Fruits Red",
"Galangal",
"Ginger",
"Ginger Mango",
"Golden Kiwi",
"Gooseberry Amla",
"Grapes Black Seedless",
"Grapes Green Seedless",
"Grapes Green Seedless Packed",
"Grapes Paneer",
"Grapes Red Globe",
"Grapes Red Globe Packed",
"Green Chilli KPN",
"Greenpeas Ooty",
"Greens Palak",
"Greens Ponnakanni Bangalore",
"Guava Big",
"Guava White",
"Iceberg Lettuce",
"Jackfruit raw",
"Kale Leaves",
"Karunai Kilangu",
"Kiwi Green",
"Knol Khol",
"Koorkan Kilangu",
"KPN-Sprouts",
"Lab Lab Long",
"Ladiesfinger",
"Leaves Leaks",
"Lemon",
"Lettuce Leaves",
"Longan Imported",
"Mango Neelam",
"Mango Senthooram",
"Mango Totapuri",
"Mangusteens Indian",
"Mosambi",
"Musk Melon Yellow",
"Muskmelon Rock",
"Nectarines",
"Onion Bellary Packed",
"Onion Big Bellary",
"Orange Nagpur",
"Orange Small",
"Orange Valencia",
"Oyster Mushroom",
"Papaya",
"Parsley Leaves",
"Parwal",
"Passion Fruit",
"Peaches Indian",
"Pears Green",
"Pears Ooty",
"Persimmon",
"Pineapple",
"Plaintain Thandu",
"Plums Imported",
"Plums Indian",
"Plums Indian Packed",
"Pomegranate Kabul",
"Potato Small",
"Potato Small Bag",
"Prunes",
"Pumpkin",
"Pumpkin cut Wrapped",
"Radish Red",
"Radish White",
"Rambutan",
"Ramsita",
"Ridge Gourd",
"Sanpa Green Chilli",
"Sapota Round",
"Seppan Kilang Arabi",
"Snake Gourd",
"Soursop Fruit",
"Spring Onion",
"Sweet Corn",
"Sweet Potato",
"Tomato Apple",
"Tomato Nadu",
"Turnip",
"Watermelon Kiran",
"Zucchini Green",
"Zucchini Yellow"
];
$class_count = [];

function classCountIndirectory($directory,$classregex,&$class_count) {
    $files = scandir($directory);
    foreach ($files as $file) {
        $filePath = $directory . '/' . $file;
        //echo $filePath . PHP_EOL;
        if (is_file($filePath)) {
            preg_match($classregex, $filePath, $matches) . PHP_EOL;
            //echo $classregex.PHP_EOL;
            $newmatches = array_shift($matches);
            array_push($class_count, $newmatches);
        } elseif (is_dir($filePath) && $file !== '.' && $file !== '..') {
            $subdirectory = $directory . '/' . $file;
            classCountIndirectory($subdirectory,$classregex,$class_count);
        }
        //echo PHP_EOL;
    }
}

if(!isset($argv[1])){
	echo "Need Directory to find the count". PHP_EOL;
	exit(0);
}
$classregex = '/(' . implode(')|(',$classes) . ')/i';
classCountIndirectory($argv[1], $classregex, $class_count);
$vals = array_count_values(array_values(array_filter($class_count)));
print_r($vals);
