path: "/media/visionai/DATA2/DEV-PYTHON/self-checkout/artifacts/data/"
# path: "/media/visionai/DATA2/DEV-PYTHON/self-checkout/artifacts/classifydata/"
# path: "/media/visionai/DATA2/DEV-PYTHON/self-checkout/artifacts/data/"
# path: "E:/DEV-PYTHON/self-checkout/artifacts/data/"

train: images/train 
val: images/val  

nc: 136
names: [
      "Amaranthus Green Bunch",
      "Amaranthus Red Bunch",
      "Apple Fuji",
      "Apple Kashmir",
      "Apple Pink Lady",
      "Apple Red Delicious",
      "Apple Royal Gala",
      "Apple Simla",
      "Ash Gourd",
      "Avocado",
      "Baby Corn",
      "Baby Potato",
      "Banana Flower",
      "Banana Leaf",
      "Banana Nendran",
      "Banana Nendran Raw",
      "Banana Red",
      "Banana Robusta",
      "Banana Stem",
      "Banana Yellaki",
      "Beans Cowpea",
      "Beetroot",
      "Bird Chilli",
      "Bitter Gourd",
      "Bitter Gourd Calcutta",
      "Blueberries",
      "Bok Choy",
      "Bottle Gourd",
      "Brinjal Black Big",
      "Brinjal Long Green",
      "Brinjal Nagpure",
      "Brinjal Purple Striped",
      "Brinjal Round Green",
      "Broad Beans",
      "Broccoli",
      "Brown Channa Sprouts",
      "Button Mushroom",
      "Button Roses",
      "Cabbage Red",
      "Capsicum Green",
      "Capsicum Red",
      "Capsicum Yellow",
      "Carrot Regular",
      "Cauliflower",
      "Celery",
      "Cherry Tomato",
      "Chilli Bhajji",
      "Chilli Green",
      "Chinese Cabbage",
      "Chow Chow",
      "Chrysanthemum Flower",
      "Cluster Beans",
      "Coccinia",
      "Coconut",
      "Coconut Tender",
      "Color",
      "Coriander",
      "Coriander Bunch",
      "Cucumber",
      "Cucumber French",
      "Cucumber Madras",
      "Curry Leaf",
      "Custard Apple",
      "Dill Leaves",
      "Dragon Fruit",
      "Drumstick",
      "French Beans",
      "Garlic",
      "Ginger",
      "Gooseberry Amla",
      "Grape Fruits",
      "Grapes Bangalore Blue",
      "Green Gram Sprouts",
      "Guava White",
      "Jujube",
      "Kiwi Imported Economy",
      "Kiwi Imported Green",
      "Knol Khol",
      "Leek",
      "Lemon",
      "Lemon Imported",
      "Lettuce Iceberg",
      "Lettuce Leafy",
      "Mango Ginger",
      "Mango Raw",
      "Mango Totapuri",
      "Marigold Flower",
      "Methi",
      "Mint Leaves",
      "Mix",
      "Mosambi",
      "Musk Melon",
      "Okra",
      "Onion Economy",
      "Onion Sambar",
      "Onion Sambar Peeled",
      "Orange",
      "Orange Imported",
      "P Guava",
      "Papaya Normal",
      "Parwal",
      "Pears Imported Green",
      "Pears Imported Red",
      "Pineapple Queen",
      "Plum",
      "Plum Imported",
      "Pomegranate Kesar",
      "Potato",
      "Pumpkin Country",
      "Pumpkin Disco",
      "Radish Long Red",
      "Radish Red",
      "Radish White",
      "Raw Papaya",
      "Ridge Gourd",
      "Sapota Round",
      "Small Colocasia",
      "Snake Gourd",
      "Spinach",
      "Spring Onion",
      "Sprouts Mix",
      "Sweet Corn",
      "Sweet Potato",
      "Sweet Tamarind",
      "Tangerine",
      "Tapioca",
      "Tinda",
      "Tomato",
      "Tomato Cherry",
      "Tomato Country",
      "Tomato Green",
      "Turnip",
      "Watermelon Kiran",
      "Yam",
      "Zucchini Green",
      "Zucchini Yellow"
]
