# path: "/media/soharab/DATA1/DEV-PYTHON/self-checkout/artifacts/data/"
path: "/Users/zeeshan/Documents/projects/self-checkout/artifacts/data/"
# path: "/media/soharab/DATA2/DEV-PYTHON/self-checkout/artifacts/data/"
# path: "C:/Users/Zeeshan.khan/vscode_projects/self-checkout/artifacts/data/"

train: images/train 
val: images/val  

nc: 17
names: [
      'Anjeer',        
      'Apple Granny Smith',
      'Apple Pink Lady',
      'Apple Royal Gala_02748',
      'Apple Shimla_73536',
      'Apple Small_35748',
      'Citron989',
      'Guava Big657',
      'Curry Leaves859',
      'Iceberg Lettuce54647',
      'Koorkan Kilangu9494',
      'Galangal9494',
      'Ladiesfinger484',
      'Grapes Black Seedless948',
      'Longan Imported_7449',
      'Grapes Paneer_94040',
      'Soursop Fruit_74849'
      # 'Apricots Fresh',
      # 'Apricots Fresh Packed',
      # 'Ash Gourd Cut',
      # 'Avocado Indian',
      # 'Baby Corn',
      # 'Banana Flower',
      # 'Banana Hills',
      # 'Banana Morris',
      # 'Banana Nadan',
      # 'Banana Nendran',
      # 'Banana Poovan',
      # 'Banana Rasthali',
      # 'Banana Red',
      # 'Banana Yelakki',
      # 'Beans Bush',
      # 'Beans Butter',
      # 'Beans Thin Cowpea',
      # 'Beetroot',
      # 'Bere Elandai',
      # 'Bitter Gourd',
      # 'Bok Choy',
      # 'Bottle Gourd',
      # 'Brinjal Black Big',
      # 'Brinjal Long',
      # 'Brinjal Purple Striped',
      # 'Broccoli',
      # 'Brussels Sprout',
      # 'Cabbage',
      # 'Cabbage Red',
      # 'Capsicum',
      # 'Capsicum Red',
      # 'Capsicum Yellow',
      # 'Carrot Ooty',
      # 'Cassave',
      # 'Cauliflower',
      # 'Chilli Long Bajji',
      # 'Chinese Cabbage',
      # 'Chow Chow',
      # 'Cluster Beans',
      # 'Coconut',
      # 'Coconut Flower',
      # 'Coriander Leaves',
      # 'Cucumber',
      # 'Custard Apple',
      # 'Dragon Fruits Red',
      # 'Golden Kiwi',
      # 'Gooseberry Amla',
      # 'Guava White',
      # 'Jackfruit raw',
      # 'Kale Leaves',
      # 'Karunai Kilangu',
      # 'Kiwi Green',
      # 'Knol Khol',
      # 'KPN-Sprouts',
      # 'Lab Lab Long',
      # 'Lemon',
      # 'Lettuce Leaves',
      # 'Mango Neelam',
      # 'Mango Totapuri',
      # 'Mangusteens Indian',
      # 'Mosambi',
      # 'Musk Melon Yellow',
      # 'Muskmelon Rock',
      # 'Nectarines',
      # 'Onion Big Bellary',
      # 'Orange Nagpur',
      # 'Orange Small',
      # 'Orange Valencia',
      # 'Oyster Mushroom',
      # 'Papaya',
      # 'Parsley Leaves',
      # 'Passion Fruit',
      # 'Pears Green',
      # 'Pears Ooty',
      # 'Pineapple',
      # 'Plums Imported',
      # 'Plums Indian',
      # 'Plums Indian Packed',
      # 'Pomegranate Kabul',
      # 'Potato Small',
      # 'Potato Small Bag',
      # 'Prunes',
      # 'Pumpkin',
      # 'Pumpkin cut Wrapped',
      # 'Radish Red',
      # 'Radish White',
      # 'Sapota Round',
      # 'Snake Gourd',
      # 'Tomato Apple',
      # 'Tomato Nadu',
      # 'Turnip',
      # 'Watermelon Kiran',
      # 'Zucchini Green',
      # 'Zucchini Yellow'
      ]