name : 'train0-classify-reliance-136classes-20epochs-original-0'
split_point : 0.85
model_variant : 'yolov8n-cls.pt'
batch : 64
epochs : 20
imgsz : 640
device : "1"
verbose : False
cos_lr : False
optimizer : 'Adam'
patience : 20
workers : 16
nbs : 64
val : True
mask_ratio : 1
lr0 : 0.01
lrf : 0.0001
