artifacts_root: artifacts

data_transfer:
  data_transfer_yaml : artifacts/yolo-config/class.yaml
 
data_ingestion:
  temp_dir : artifacts/temp
  temp_labels_dir : artifacts/temp/labels
  temp_mask_dir : artifacts/temp/mask
  original_image_dir : artifacts/temp/original
  yolo_seg_config_file: artifacts/yolo-config/task-seg.yaml

data_transformation:
  temp_labels_dir : artifacts/temp/labels
  original_image_dir : artifacts/temp/original
  train_label_dir: artifacts/data/labels/train
  test_label_dir: artifacts/data/labels/val
  train_image_dir : artifacts/data/images/train
  test_image_dir: artifacts/data/images/val
  yolo_config_dir: artifacts/yolo-config

model_training:
  yolo_config_dir: artifacts/yolo-config
  yolo_seg_config_file: artifacts/yolo-config/task-seg.yaml


model_evaluation:
  train_image_dir: artifacts/temp/original
# model_pusher:
#   training: artifacts/model_training/model_pickle
#   s3_bucket_pickle : artifacts/model_pusher/s3_bucket_pickle

